export default defineEventHandler(() => {
  return {
    cerita: [
      {
        id: 1,
        imageProfile:
          "https://uemkaem.id/images/logo/thumbnail/1661330604.jpeg",
        nameProfile: "Sketsa Mandiri",
        title: "Desain Kabinet untuk flat TV",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        image: "https://uemkaem.id/images/news/1661329928.jpeg",
        counLike: 10,
        countComment: 2,
      },
      {
        id: 2,
        imageProfile: "https://uemkaem.id/images/logo/thumbnail/1661157242.png",
        nameProfile: "Kobar Tanamama",
        title: "Cerita Usaha 2",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        image: "https://uemkaem.id/images/news/1658474823.jpeg",
        counLike: 12,
        countComment: 2,
      },
      {
        id: 3,
        imageProfile: "https://uemkaem.id/images/logo/thumbnail/1661157242.png",
        nameProfile: "Kobar Tanamama",
        title: "Cerita Usaha 3",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        image: "https://uemkaem.id/images/news/1658473611.jpeg",
        counLike: 4,
        countComment: 1,
      },
      {
        id: 4,
        imageProfile: "https://uemkaem.id/images/logo/thumbnail/1661157242.png",
        nameProfile: "Kobar Tanamama",
        title: "Cerita Usaha 4",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        image: "https://uemkaem.id/images/news/1658473574.jpeg",
        counLike: 10,
        countComment: 2,
      },
      {
        id: 5,
        imageProfile: "https://uemkaem.id/images/logo/thumbnail/1661157242.png",
        nameProfile: "Kobar Tanamama",
        title: "Kobar Tanamama",
        description: "Pempek paket harga lebih ekonomis, yuk dipesen 😊😊😊 ",
        image: "https://uemkaem.id/images/news/1658473549.jpeg",
        counLike: 10,
        countComment: 2,
      },
      {
        id: 6,
        imageProfile: "https://picsum.photos/seed/picsum/200/300",
        nameProfile: "Toko Sebarguna",
        title: "Cerita Usaha Lainnya",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        image: "https://picsum.photos/200/300",
        counLike: 10,
        countComment: 2,
      },
    ],
  };
});
